"""crear tablas iniciales v2

Revision ID: 5482eda3ea79
Revises: a1eded061ee5
Create Date: 2025-03-02 19:14:36.628787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5482eda3ea79'
down_revision: Union[str, None] = 'a1eded061ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_status',
    sa.Column('statusuuid', sa.UUID(), nullable=False),
    sa.Column('statusname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('statusuuid'),
    sa.UniqueConstraint('statusname')
    )
    op.create_index(op.f('ix_appointment_status_statusuuid'), 'appointment_status', ['statusuuid'], unique=True)
    op.create_table('categories',
    sa.Column('categoryuuid', sa.UUID(), nullable=False),
    sa.Column('categoryname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('categoryuuid'),
    sa.UniqueConstraint('categoryname')
    )
    op.create_index(op.f('ix_categories_categoryuuid'), 'categories', ['categoryuuid'], unique=True)
    op.create_table('payment_status',
    sa.Column('statusuuid', sa.UUID(), nullable=False),
    sa.Column('statusname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('statusuuid'),
    sa.UniqueConstraint('statusname')
    )
    op.create_index(op.f('ix_payment_status_statusuuid'), 'payment_status', ['statusuuid'], unique=True)
    op.create_table('roles',
    sa.Column('roleuuid', sa.UUID(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('roleuuid'),
    sa.UniqueConstraint('rolename')
    )
    op.create_index(op.f('ix_roles_roleuuid'), 'roles', ['roleuuid'], unique=True)
    op.create_table('services',
    sa.Column('serviceuuid', sa.UUID(), nullable=False),
    sa.Column('servicename', sa.String(length=50), nullable=False),
    sa.Column('serviceprice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoryuuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categoryuuid'], ['categories.categoryuuid'], ),
    sa.PrimaryKeyConstraint('serviceuuid')
    )
    op.create_index(op.f('ix_services_serviceuuid'), 'services', ['serviceuuid'], unique=True)
    op.create_table('users',
    sa.Column('useruuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('useremail', sa.String(length=50), nullable=False),
    sa.Column('userpass', sa.String(), nullable=False),
    sa.Column('roleuuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['roleuuid'], ['roles.roleuuid'], ),
    sa.PrimaryKeyConstraint('useruuid')
    )
    op.create_index(op.f('ix_users_useremail'), 'users', ['useremail'], unique=True)
    op.create_index(op.f('ix_users_useruuid'), 'users', ['useruuid'], unique=True)
    op.create_table('staff',
    sa.Column('staffuuid', sa.UUID(), nullable=False),
    sa.Column('staffname', sa.String(length=50), nullable=False),
    sa.Column('useruuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['useruuid'], ['users.useruuid'], ),
    sa.PrimaryKeyConstraint('staffuuid')
    )
    op.create_index(op.f('ix_staff_staffuuid'), 'staff', ['staffuuid'], unique=True)
    op.create_table('appointments',
    sa.Column('appointmentuuid', sa.UUID(), nullable=False),
    sa.Column('clientuuid', sa.UUID(), nullable=False),
    sa.Column('staffuuid', sa.UUID(), nullable=False),
    sa.Column('serviceuuid', sa.UUID(), nullable=False),
    sa.Column('statusuuid', sa.UUID(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clientuuid'], ['users.useruuid'], ),
    sa.ForeignKeyConstraint(['serviceuuid'], ['services.serviceuuid'], ),
    sa.ForeignKeyConstraint(['staffuuid'], ['staff.staffuuid'], ),
    sa.ForeignKeyConstraint(['statusuuid'], ['appointment_status.statusuuid'], ),
    sa.PrimaryKeyConstraint('appointmentuuid')
    )
    op.create_index(op.f('ix_appointments_appointmentuuid'), 'appointments', ['appointmentuuid'], unique=True)
    op.create_table('payments',
    sa.Column('paymentuuid', sa.UUID(), nullable=False),
    sa.Column('appointmentuuid', sa.UUID(), nullable=False),
    sa.Column('paymentamount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paymentmethod', sa.String(), nullable=False),
    sa.Column('statusuuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointmentuuid'], ['appointments.appointmentuuid'], ),
    sa.ForeignKeyConstraint(['statusuuid'], ['payment_status.statusuuid'], ),
    sa.PrimaryKeyConstraint('paymentuuid')
    )
    op.create_index(op.f('ix_payments_paymentuuid'), 'payments', ['paymentuuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_paymentuuid'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_appointments_appointmentuuid'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_staff_staffuuid'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_users_useruuid'), table_name='users')
    op.drop_index(op.f('ix_users_useremail'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_serviceuuid'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_roles_roleuuid'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_payment_status_statusuuid'), table_name='payment_status')
    op.drop_table('payment_status')
    op.drop_index(op.f('ix_categories_categoryuuid'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_appointment_status_statusuuid'), table_name='appointment_status')
    op.drop_table('appointment_status')
    # ### end Alembic commands ###
